<a href="https://colab.research.google.com/github/charan-debug/101-APPLIED-LINEAR-ALGEBRA/blob/main/4_Eigen_Values_and_Eigen_Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

# create numpy 2d-array
Matrix = np.array([[6, 5],[1, 7]])

print("The Matrix is :\n",m)

# finding eigenvalues and eigenvectors
x, y = np.linalg.eig(Matrix)

# printing eigen values
print("Printing the Eigen values of the Matrix:\n",x)

# printing eigen vectors
print(" Printing Right eigenvectors of the Matrix:\n",y)


The Matrix is :
 [[6 5]
 [1 7]]
Printing the Eigen values of the Matrix:
 [4.20871215 8.79128785]
 Printing Right eigenvectors of the Matrix:
 [[-0.94140906 -0.87315384]
 [ 0.33726692 -0.48744474]]


In [13]:
import numpy as np

def input_matrix():
    n = int(input("Enter the size of the square matrix (e.g., 2 for 2x2, 3 for 3x3): "))
    matrix = []

    print("Enter the elements row by row:")
    for _ in range(n):
        row = list(map(float, input().split()))
        if len(row) != n:
            print("Invalid input. Please enter exactly {} elements for each row.".format(n))
            return None
        matrix.append(row)

    return np.array(matrix)

# Call the function to input the matrix
matrix = input_matrix()

if matrix is not None:
    print("The Matrix is :\n", matrix)

    # Finding eigenvalues and eigenvectors
    w, v = np.linalg.eig(matrix)

    # Printing eigenvalues
    print("Printing the Eigen values of the Matrix:\n", w)

    # Printing eigenvectors
    print("Printing Right eigenvectors of the Matrix:\n", v)


Enter the size of the square matrix (e.g., 2 for 2x2, 3 for 3x3): 3
Enter the elements row by row:
1 1 1
1 1 1
1 1 1
The Matrix is :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Printing the Eigen values of the Matrix:
 [-2.22044605e-16  3.00000000e+00  0.00000000e+00]
Printing Right eigenvectors of the Matrix:
 [[-0.81649658  0.57735027  0.        ]
 [ 0.40824829  0.57735027 -0.70710678]
 [ 0.40824829  0.57735027  0.70710678]]
