<a href="https://colab.research.google.com/github/charan-debug/101-APPLIED-LINEAR-ALGEBRA/blob/main/5_Singular_Value_Decomposition_using_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Singular Value Decomposition using NumPy

***np.linalg.svd*** decomposes a given matrix A into three matrices U, S, and VT, such that A can be reconstructed as A = U @ np.diag(S) @ VT.

This decomposition is fundamental in various numerical algorithms and is widely used in linear algebra and data analysis.

U: This is the matrix of left singular vectors. It contains the orthonormal basis vectors for the column space of the original matrix A. The columns of U are called the left singular vectors.***The order is m x m***

S: This is a 1D array containing the singular values of the matrix A. The singular values are non-negative real numbers and are ordered in descending order.***The  order of the matrix is  m x n***

VT: This is the transpose of the matrix of right singular vectors. It contains the orthonormal basis vectors for the row space of the original matrix A. The rows of VT are called the right singular vectors. ***The  order of the matrix is  n x n***




In [1]:
import numpy as np

# Create a matrix A for SVD
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Perform SVD
U, S, VT = np.linalg.svd(A)

# U is the left singular vectors of order m x m
print("Left singular vectors U:")
print(U)

# S is the singular values (in descending order) of order m x n
print("Singular values S:")
print(S)

# VT is the right singular vectors (transpose of V) of order n x n
print("Right singular vectors V^T:")
print(VT)


Left singular vectors U:
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Singular values S:
[1.68481034e+01 1.06836951e+00 4.41842475e-16]
Right singular vectors V^T:
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [2]:
import numpy as np

# Input the matrix dimensions
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))

# Input the elements of the matrix
print(f"Enter the elements of the {rows}x{cols} matrix row by row (separate values by space):")
matrix = []

for _ in range(rows):
    row = list(map(float, input().split()))
    if len(row) != cols:
        print(f"Invalid input. Please enter exactly {cols} elements for each row.")
        exit()
    matrix.append(row)

# Perform SVD
A = np.array(matrix)
U, S, VT = np.linalg.svd(A)

# U is the left singular vectors of order m x m
print("Left singular vectors U:")
print(U)

# S is the singular values (in descending order) m x n
print("Singular values S:")
print(S)

# VT is the right singular vectors (transpose of V)of order n x n
print("Right singular vectors V^T:")
print(VT)


Enter the number of rows: 2
Enter the number of columns: 2
Enter the elements of the 2x2 matrix row by row (separate values by space):
1 2
3 1
Left singular vectors U:
[[-0.52573111 -0.85065081]
 [-0.85065081  0.52573111]]
Singular values S:
[3.61803399 1.38196601]
Right singular vectors V^T:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
